name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, xml, ctype, json, tokenizer, bcmath, zip, gd, curl, sqlite3

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

    - name: Generate Laravel Application key
      run: php artisan key:generate

    - name: Remove Composer dev dependencies
      run: composer install --no-dev --optimize-autoloader --prefer-dist --no-interaction --no-scripts

    - name: Clear cache
      run: php artisan optimize:clear

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Install npm dependencies
      run: npm install

    - name: Run Laravel Mix
      run: npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_usename }}
        password: ${{ secrets.ftp_password }}
